# Generated by Django 2.2.6 on 2020-01-04 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='genres',
            field=models.CharField(choices=[('Action', 'Action'), ('Thriller', 'Thriller'), ('Sci-Fi', 'Sci-Fi'), ('War', 'War')], max_length=50),
        ),
        migrations.AlterField(
            model_name='preference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
