# Generated by Django 2.2.6 on 2020-01-04 11:13

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200104_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='genres',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Action', 'Action'), ('Thriller', 'Thriller'), ('Sci-Fi', 'Sci-Fi'), ('War', 'War')], max_length=26),
        ),
    ]
